// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWUiEeOHjezfetL9uM5HIFC8Hrk1aEEqc',
    appId: '1:406459429189:android:daedc2d229e4848f100e2c',
    messagingSenderId: '406459429189',
    projectId: 'flutter-quiz-d9edb',
    storageBucket: 'flutter-quiz-d9edb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Mny4Ij8ZWdhS0dl_34M6_eyt8SPqXQg',
    appId: '1:406459429189:ios:e91c4aff8e5e258f100e2c',
    messagingSenderId: '406459429189',
    projectId: 'flutter-quiz-d9edb',
    storageBucket: 'flutter-quiz-d9edb.firebasestorage.app',
    androidClientId: '406459429189-fan77tmt3uaqia0bdaohupvu7otnles0.apps.googleusercontent.com',
    iosClientId: '406459429189-1o1gr4u02geb2jejot2vsi8nmldf5rvn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

}